Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/usr/local/lib/python3.9/site-packages/nbclient/client.py", line 1087, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/usr/local/lib/python3.9/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/usr/local/lib/python3.9/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.9/site-packages/nbclient/client.py", line 540, in async_execute
    await self.async_execute_cell(
  File "/usr/local/lib/python3.9/site-packages/nbclient/client.py", line 832, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/usr/local/lib/python3.9/site-packages/nbclient/client.py", line 740, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply['content'])
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import nashpy as nash

A = np.array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 
              [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0],
              [2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 0],
              [3, 3, 3, 3, 3, 3, 3, 3, 0, 0, 0],
              [4, 4, 4, 4, 4, 4, 4, 0, 0, 0, 0],
              [5, 5, 5, 5, 5, 5, 0, 0, 0, 0, 0],
              [6, 6, 6, 6, 6, 0, 0, 0, 0, 0, 0],
              [7, 7, 7, 7, 0, 0, 0, 0, 0, 0, 0],
              [8, 8, 8, 0, 0, 0, 0, 0, 0, 0, 0],
              [9, 9, 0, 0, 0, 0, 0, 0, 0, 0, 0],
              [10, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
             ])

B = np.array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10], 
              [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0], 
              [0, 1, 2, 3, 4, 5, 6, 7, 8, 0, 0], 
              [0, 1, 2, 3, 4, 5, 6, 7, 0, 0, 0], 
              [0, 1, 2, 3, 4, 5, 6, 0, 0, 0, 0], 
              [0, 1, 2, 3, 4, 5, 0, 0, 0, 0, 0], 
              [0, 1, 2, 3, 4, 0, 0, 0, 0, 0, 0], 
              [0, 1, 2, 3, 0, 0, 0, 0, 0, 0, 0], 
              [0, 1, 2, 0, 0, 0, 0, 0, 0, 0, 0], 
              [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0], 
              [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 
             ])
divide_the_dollar = nash.Game(A, B)

num_nash_eq = 0
for eq in divide_the_dollar.support_enumeration():
    print(eq)
    if num_nash_eq == 15:
        # there are infinitely many Nash equilibrium, so only print out the first 15
        break
    num_nash_eq += 1
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
[0;32m<ipython-input-1-04e319d45cd9>[0m in [0;36m<module>[0;34m[0m
[1;32m      1[0m [0;32mimport[0m [0mnashpy[0m [0;32mas[0m [0mnash[0m[0;34m[0m[0;34m[0m[0m
[1;32m      2[0m [0;34m[0m[0m
[0;32m----> 3[0;31m A = np.array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 
[0m[1;32m      4[0m               [0;34m[[0m[0;36m1[0m[0;34m,[0m [0;36m1[0m[0;34m,[0m [0;36m1[0m[0;34m,[0m [0;36m1[0m[0;34m,[0m [0;36m1[0m[0;34m,[0m [0;36m1[0m[0;34m,[0m [0;36m1[0m[0;34m,[0m [0;36m1[0m[0;34m,[0m [0;36m1[0m[0;34m,[0m [0;36m1[0m[0;34m,[0m [0;36m0[0m[0;34m][0m[0;34m,[0m[0;34m[0m[0;34m[0m[0m
[1;32m      5[0m               [0;34m[[0m[0;36m2[0m[0;34m,[0m [0;36m2[0m[0;34m,[0m [0;36m2[0m[0;34m,[0m [0;36m2[0m[0;34m,[0m [0;36m2[0m[0;34m,[0m [0;36m2[0m[0;34m,[0m [0;36m2[0m[0;34m,[0m [0;36m2[0m[0;34m,[0m [0;36m2[0m[0;34m,[0m [0;36m0[0m[0;34m,[0m [0;36m0[0m[0;34m][0m[0;34m,[0m[0;34m[0m[0;34m[0m[0m

[0;31mNameError[0m: name 'np' is not defined
NameError: name 'np' is not defined

